name: 'dbt_search'
version: '1.0.0'
config-version: 2

profile: 'dbt_search'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  dbt_search:                      # ← your actual project name
    staging:                  # your intermediate folder
      +materialized: table       
    prod:                  # your intermediate folder
      +materialized: table    

  elementary:
    +schema: "elementary"