{{ config(materialized='table',
tags=["tribal_health"]) }}


select
    _id,
    "end",
    "Area",
    "Date",
    _tags,
    _uuid,
    start,
    _index,
    _notes,
    _status,
    __version__,
    "Village_Name",
    "Village_GPS_",
    "Place_4_Photo",
    _submitted_by,
    "Place_1___Name",
    "Place_2___Name",
    "Place_3___Name",
    "Place_4___Name",
    "Place_1___Photo",
    "Place_2___Photo",
    "Place_3___Photo",
    total_attendance,
    _submission_time,
    "Place_1_Photo_URL",
    "Place_2_Photo_URL",
    "Place_3_Photo_URL",
    "Place_4_Photo_URL",
    "Search_Driver_Name",
    _validation_status,
    "Place_1___Attendance",
    "Place_2___Attendance",
    "Place_3___Attendance",
    "Place_4___Attendance",
    "Village_GPS__altitude",
    "Village_GPS__latitude",
    "Village_GPS__longitude",
    "Village_GPS__precision",
    "Time_of_Health_Education",
    "Was_Health_Worker_Present__",
    "Time_of_Health_Education_End_",
    "Topic_of_the_Health_Education",
    "Was_Health_Education_Conducted",
    "Health_Education_Given_By__Name_",
    number_of_places_with_health_education,
    "Reason_Not_Conducted_Was_Health_Worker_Present_",
    _airbyte_raw_id,
    _airbyte_extracted_at,
    _airbyte_meta

from {{ ref('staging_tribal_health_education') }}